# Generated by Django 5.1 on 2024-09-21 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0003_vehicle_model_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(max_length=100)),
                ('maintenance_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('service_provider', models.CharField(max_length=250)),
                ('cost', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle_model')),
            ],
        ),
    ]
