# Generated by Django 5.1 on 2024-08-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle_model',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle_model',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
