# Generated by Django 5.1 on 2024-09-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle_model',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
