# Generated by Django 5.1 on 2024-09-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_model',
            name='buyer_contact',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='sales_model',
            name='buyer_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='sales_model',
            name='sale_price',
            field=models.FloatField(blank=True),
        ),
    ]
